<a href="https://colab.research.google.com/github/birhanukassahunabuye-hue/data-analysis-with-python/blob/main/pandasexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
#population in millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [ ]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [ ]:
g7_pop[0]

np.float64(35.467)

In [ ]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
g7_pop.index = [
    'canada',
    'france',
    'germany',
    'italy',
    'japan',
    'united kingdom',
    'united states',
]
g7_pop

canada             35.467
france             63.951
germany            80.940
italy              60.665
japan             127.061
united kingdom     64.511
united states     318.523
dtype: float64

In [ ]:
g7_pop['germany']

np.float64(80.94)

In [ ]:
g7_pop.iloc[4]

np.float64(127.061)

In [ ]:
g7_pop['canada': 'italy']

canada     35.467
france     63.951
germany    80.940
italy      60.665
dtype: float64

In [ ]:
g7_pop > 70

canada            False
france            False
germany            True
italy             False
japan              True
united kingdom    False
united states      True
dtype: bool

In [ ]:
g7_pop[g7_pop > 70]

germany           80.940
japan            127.061
united states    318.523
dtype: float64

In [ ]:
g7_pop.mean()

np.float64(107.30257142857144)

In [ ]:
g7_pop.std()

97.24996987121581

In [ ]:
g7_pop[g7_pop > g7_pop.mean()]

japan            127.061
united states    318.523
dtype: float64

In [ ]:
#using or, and , or in pandas
g7_pop[(g7_pop > 80) & (g7_pop < 200)]

germany     80.940
japan      127.061
dtype: float64

In [ ]:
import numpy as np
import pandas as pd

In [16]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
        'population': [35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523],
        'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
        ],
        'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
        ],
        'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
        ],
       'continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America']}, columns = ['population', 'GDP', 'Surface Area', 'HDI', 'continent'])

In [ ]:
df

   population       GDP  Surface Area    HDI continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 412.0+ bytes

In [ ]:
df.columns

Index(['population', 'GDP', 'Surface Area', 'HDI', 'continent'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [ ]:
df.size

35

In [ ]:
df.shape

(7, 5)

In [ ]:
df.describe()

       population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [ ]:
df.dtypes

population      float64
GDP               int64
Surface Area      int64
HDI             float64
continent        object
dtype: object

In [ ]:
df.iloc[-1]

population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
continent        America
Name: 6, dtype: object

In [ ]:
df.index = [
    'canada',
    'france',
    'germany',
    'italy',
    'japan',
    'united kingdom',
    'united states',
]

In [ ]:
df

                population       GDP  Surface Area    HDI continent
canada              35.467   1785387       9984670  0.913   America
france              63.951   2833687        640679  0.888    Europe
germany             80.940   3874437        357114  0.916    Europe
italy               60.665   2167744        301336  0.873    Europe
japan              127.061   4602367        377930  0.891      Asia
united kingdom      64.511   2950039        242495  0.907    Europe
united states      318.523  17348075       9525067  0.915   America

In [ ]:
df.loc['japan']

population      127.061
GDP             4602367
Surface Area     377930
HDI               0.891
continent          Asia
Name: japan, dtype: object

In [ ]:
df['population']

canada             35.467
france             63.951
germany            80.940
italy              60.665
japan             127.061
united kingdom     64.511
united states     318.523
Name: population, dtype: float64

In [ ]:
df.loc['france':'italy']

         population      GDP  Surface Area    HDI continent
france       63.951  2833687        640679  0.888    Europe
germany      80.940  3874437        357114  0.916    Europe
italy        60.665  2167744        301336  0.873    Europe

In [ ]:
df.loc['france':'italy', 'population']

france     63.951
germany    80.940
italy      60.665
Name: population, dtype: float64

In [ ]:
df.iloc[1:3]

         population      GDP  Surface Area    HDI continent
france       63.951  2833687        640679  0.888    Europe
germany      80.940  3874437        357114  0.916    Europe

In [ ]:
df.iloc[1:3, 4]

france     Europe
germany    Europe
Name: continent, dtype: object

In [ ]:
df.loc[df['population'] > 70]

               population       GDP  Surface Area    HDI continent
germany            80.940   3874437        357114  0.916    Europe
japan             127.061   4602367        377930  0.891      Asia
united states     318.523  17348075       9525067  0.915   America

In [ ]:
df['population'] > 70

canada            False
france            False
germany            True
italy             False
japan              True
united kingdom    False
united states      True
Name: population, dtype: bool

In [17]:
df['gdp per capita'] = df['GDP'] / df['population']

In [18]:
df['language'] = 'English'

In [19]:
df

,population,GDP,Surface Area,HDI,continent,gdp per capita,language
0,35.467,1785387,9984670,0.913,America,50339.385908,English
1,63.951,2833687,640679,0.888,Europe,44310.284437,English
2,80.940,3874437,357114,0.916,Europe,47868.013343,English
3,60.665,2167744,301336,0.873,Europe,35733.025633,English
4,127.061,4602367,377930,0.891,Asia,36221.712406,English
5,64.511,2950039,242495,0.907,Europe,45729.239975,English
6,318.523,17348075,9525067,0.915,America,54464.120330,English